title: Jae Yeon Kim
url: "https://jaeyk.github.io/"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-127195649-1

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/researcher/"
 - name: "CV"
   link: "CV_Jae_Yeon_Kim.pdf"
 #- name: "resume"
 #  link: "resume_Jae_Yeon_Kim.pdf"
 - name: "GitHub"
   link: https://github.com/jaeyk
 - name: "Google Scholar"
   link: https://scholar.google.com/citations?user=v2h903EAAAAJ&hl=en
 - name: "Bluesky"
   link: https://bsky.app/profile/jaeyeonkim.bsky.social
 - name: "LinkedIn"
   link: https://www.linkedin.com/in/jae-yeon-kim-694764229/