---
title: "Bio"
---

I am an Assistant Professor of Public Policy at [the University of North Carolina at Chapel Hill](https://publicpolicy.unc.edu/person/jae-yeon-kim/), and a non-resident Research Fellow at the Harvard Kennedy School and a [Better Government Lab](https://www.bettergovernmentlab.org/) Fellow at the University of Michigan's Ford School of Public Policy. I co-founded the [Data for Good Roundtables](https://sites.google.com/view/d4g-roundtables?usp=sharing) and serve on the Advisory Council of [the Summer Institute in Computational Social Science](https://sicss.io/people), the Procurement Committee at [the GovAI Coalition](https://www.sanjoseca.gov/your-government/departments-offices/information-technology/ai-reviews-algorithm-register/govai-coalition), and the APSA Task Force on Artificial Intelligence. In Spring 2027, I will be on research leave and visiting UC Berkeley's [Berkeley Economy & Society Initiative](https://besi.berkeley.edu/).

Previously, I worked as a Senior Data Scientist at [Code for America](https://codeforamerica.org/), where I collaborated with the U.S. government to improve access to safety net programs. I also served as an Assistant Research Scientist at the SNF Agora Institute at Johns Hopkins University, where I co-developed [the Mapping the Modern Agora Project.](https://snfagora.jhu.edu/our-work/research-projects/mapping-the-modern-agora/) I earned my Ph.D. in Political Science from the University of California, Berkeley.

My research focuses on making policy implementation work. I study administrative burden in safety net programs, the relationship between civic infrastructure and democratic governance, and how state and local governments use artificial intelligence to deliver public services.

I'm currently working on a book project titled [*Unseen and Uncounted*](https://jaeyk.github.io/book_projects/books.html), which examines how local governments counted and delivered services to immigrant communities during the War on Poverty, and how these interactions shaped new racial group formations now known as Asian Americans and Latinos. My second book project focuses on the role of mission-driven evaluation in empowering organizations and delivering results, from improving safety net delivery and strengthening civic infrastructure to advancing AI justice.

I use a wide range of methods, including big data and AI, field experiments, archival research, and human-centered design. I often collaborate with government and nonprofit partners to produce research that directly informs policy and improves practice.

My research has been published or is forthcoming in *Nature Human Behaviour*, *Journal of Policy Analysis and Management*, *Nature: Scientific Data* [2x], *Perspectives on Politics* [2x], *Political Research Quarterly* [2x], *Journal of Experimental Political Science*, *Studies in American Political Development*, and Cambridge University Press, among others.

I am the recipient of the Paul Volcker Junior Scholar Research Grant Award in Public Administration (2025), Emerging Scholar Award in Civic Engagement (2024), and the Best Dissertation Award in Urban and Local Politics (2022) from the American Political Science Association, as well as the Don T. Nakanishi Award for Distinguished Scholarship and Service in Asian Pacific American Politics (2020) from the Western Political Science Association.
