---
title: "Personal"
---

My career path has been non-linear, spanning academia, public, and private sectors, but my focus has always been on increasing public access to resources. When I was still an undergraduate, I helped Korea University, my alma mater, launch one of the first Massive Open Online Courses in South Korea. Additionally, I was an activist for the Korean branch of Creative Commons, which initiated the Korean open government movement. I also served on the user service advisory board of Naver, the largest internet company in Korea, as its youngest and only college student member. After college, I took my first job as a product manager at a software startup in Seoul. In 2014, I moved to the U.S. for my graduate studies. After earning my Ph.D. from UC Berkeley, I did my postdoc training at Johns Hopkins, worked as a tenure-track assistant professor at a policy school in South Korea, and served as a data scientist in the U.S. public sector. I returned to academia to pursue my own intellectual agenda.

As a first-generation immigrant and college student from a working-class family, I am where I am today because of the generous support of my advisors and other mentors. I am committed to giving back by teaching and mentoring students from underserved populations.