// Auto-generated from index.qmd by generate_calendar.R
// Do not edit this file directly — update badge events in index.qmd,
// then run: quarto render
//
// Event type colors (future):  Talk #388e3c | Panel #1976d2 | Discussant #00796b | Participant #6d4c41
// Past events: #aaaaaa at 55% opacity

document.addEventListener('DOMContentLoaded', function () {
  var calendarEl = document.getElementById('calendar');
  if (!calendarEl) return;

  var events = [
    {
      title: "2026 Veritas Scholars Summit",
      start: "2026-06-16",
      color: "#6d4c41",
      url: "https://summit.veritas.org/scholars-summit",
      extendedProps: { org: "", host: "", place: "Park City, Utah, USA", type: "badge-participant", past: false }
    },
    {
      title: "The Future of Quantitative Social Science in an Age of Artificial Intelligenc",
      start: "2026-05-01",
      color: "#388e3c",
      extendedProps: { org: "University of Toronto", host: "Rohan Alexander", place: "Toronto, Canada", type: "badge-talk", past: false }
    },
    {
      title: "MPP Social",
      start: "2026-04-10",
      color: "#388e3c",
      extendedProps: { org: "", host: "Douglas MacKay", place: "Chapel Hill, NC, USA", type: "badge-talk", past: false }
    },
    {
      title: "National Science Foundation (NSF) Human Networks and Data Science – Core Research Panel",
      start: "2026-04-09",
      color: "#1976d2",
      url: "https://www.nsf.gov/funding/opportunities/hnds-human-networks-data-science",
      extendedProps: { org: "", host: "", place: "Virtual", type: "badge-panel", past: false }
    },
    {
      title: "Institute for AI and Social Innovation",
      start: "2026-03-25",
      color: "#388e3c",
      extendedProps: { org: "Yonsei University", host: "Wha Sun Jho", place: "Virtual", type: "badge-talk", past: false }
    },
    {
      title: "Economic Democracy Initiative Workshop",
      start: "2026-03-17",
      color: "#00796b",
      extendedProps: { org: "Columbia University", host: "Alexander Hertel-Fernandez", place: "Virtual", type: "badge-discussant", past: false }
    },
    {
      title: "Data-Driven EnviroLab",
      start: "2026-03-09",
      color: "#388e3c",
      url: "https://datadrivenlab.org/",
      extendedProps: { org: "UNC Chapel Hill", host: "Angel Hsu", place: "Chapel Hill, NC, USA", type: "badge-talk", past: false }
    },
    {
      title: "Source Code AI Trust & Fairness Co-Creation Forum",
      start: "2026-03-04",
      color: "#6d4c41",
      url: "https://fas.org/",
      extendedProps: { org: "Federation of American Scientists", host: "", place: "Washington, DC, USA", type: "badge-participant", past: false }
    },
    {
      title: "Conference on Society-Centered AI",
      start: "2026-02-14",
      color: "#aaaaaa",
      url: "https://sites.duke.edu/scai/",
      extendedProps: { org: "Duke University", host: "", place: "Durham, NC, USA", type: "badge-talk", past: true }
    },
    {
      title: "Institute of Governmental Studies",
      start: "2025-11-19",
      color: "#aaaaaa",
      extendedProps: { org: "Korea University", host: "Jun Koo", place: "Virtual", type: "badge-talk", past: true }
    },
    {
      title: "Virtual Job Market Event",
      start: "2025-11-18",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "Dept. of Political Science & IR, University of Southern California", place: "Virtual", type: "badge-panel", past: true }
    },
    {
      title: "Association for Public Policy Analysis and Management (APPAM)",
      start: "2025-11-12",
      color: "#aaaaaa",
      url: "https://convention2.allacademic.com/one/appam/appam25/index.php?PHPSESSID=e5dt3n10fmreghdqs05jjdnik2&cmd=Online+Program+Search&program_focus=fulltext_search&search_mode=content&offset=0&search_text=jae+yeon+kim",
      extendedProps: { org: "", host: "", place: "Seattle, WA, USA", type: "badge-panel", past: true }
    },
    {
      title: "The Gov AI Coalition Summit",
      start: "2025-11-05",
      color: "#aaaaaa",
      url: "https://events.govtech.com/GovAI-Coalition-Summit",
      extendedProps: { org: "", host: "GovAI Coalition and the City of San José", place: "San José Convention Center, CA, USA", type: "badge-participant", past: true }
    },
    {
      title: "New York City Mayor's Office of Economic Opportunity (NYC Opportunity)",
      start: "2025-10-30",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "Sophia Tareen", place: "Virtual", type: "badge-talk", past: true }
    },
    {
      title: "Virtual Job Market Event",
      start: "2025-10-30",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "Dept. of Political Science, UC Berkeley, feat. Natalia Garbiras-Díaz", place: "Virtual", type: "badge-panel", past: true }
    },
    {
      title: "PRIISM Seminar Series",
      start: "2025-10-22",
      color: "#aaaaaa",
      url: "https://steinhardt.nyu.edu/priism/events/upcoming-events",
      extendedProps: { org: "NYU", host: "Klint Kanopka and Ravi Shroff", place: "Virtual", type: "badge-talk", past: true }
    },
    {
      title: "Better Government Lab Research Treat",
      start: "2025-10-16",
      color: "#aaaaaa",
      extendedProps: { org: "Georgetown McCourt School of Public Policy", host: "", place: "Washington, DC, USA", type: "badge-participant", past: true }
    },
    {
      title: "Tech and Innovation Speaker Series",
      start: "2025-10-15",
      color: "#aaaaaa",
      url: "https://www.eventbrite.com/e/move-fast-without-breaking-things-how-smarter-ai-procurement-can-transform-tickets-1735067777429?aff=oddtdtcreator&fbclid=IwY2xjawNNAfdleHRuA2FlbQIxMQABHnsxf4GYAeRsWTlxWK-H9CRIqIByrPn9tESrSAf8cxK4URtCHR5cuYKYvC-5_aem_SHj7mHP6-Rd1QymDv3xcVA",
      extendedProps: { org: "Johns Hopkins SAIS", host: "", place: "Washington, DC, USA", type: "badge-talk", past: true }
    },
    {
      title: "Inequality Working Group Seminar",
      start: "2025-09-30",
      color: "#aaaaaa",
      url: "https://bridges.eaamo.org/working_groups/inequality/",
      extendedProps: { org: "EAAMO (Equity and Access in Algorithms, Mechanisms, and Optimization)", host: "", place: "Virtual", type: "badge-talk", past: true }
    },
    {
      title: "American Political Science Association (APSA)",
      start: "2025-09-11",
      color: "#aaaaaa",
      url: "https://convention2.allacademic.com/one/apsa/apsa25/index.php?PHPSESSID=q29h0kdgp0ikoco6u9j6vdt6t9&cmd=Online+Program+Search&program_focus=fulltext_search&search_mode=content&offset=0&search_text=jae+yeon+kim",
      extendedProps: { org: "", host: "", place: "Vancouver, Canada", type: "badge-panel", past: true }
    },
    {
      title: "New Faculty Orientation",
      start: "2025-08-14",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "UNC-CH", place: "Chapel Hill, NC, USA", type: "badge-participant", past: true }
    },
    {
      title: "Annual Research Conference on the American Political Economy",
      start: "2025-07-29",
      color: "#aaaaaa",
      url: "https://www.americanpoliticaleconomy.org/events/annual-conference",
      extendedProps: { org: "", host: "", place: "Virtual", type: "badge-panel", past: true }
    },
    {
      title: "Korea Foundation for Advanced Studies",
      start: "2025-06-27",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "", place: "Seoul, South Korea", type: "badge-talk", past: true }
    },
    {
      title: "Dept. of Political Science & IR",
      start: "2025-06-26",
      color: "#aaaaaa",
      extendedProps: { org: "Seoul National University", host: "Seo-young Silvia Kim", place: "Seoul, South Korea", type: "badge-panel", past: true }
    },
    {
      title: "Public Management Research Conference (PMRC)",
      start: "2025-06-26",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "", place: "Seoul, South Korea", type: "badge-panel", past: true }
    },
    {
      title: "Korea-Finland Innovation Forum",
      start: "2025-06-25",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "Yonsei University and the Embassy of Finland, Seoul", place: "Seoul, South Korea", type: "badge-panel", past: true }
    },
    {
      title: "KIXLAB",
      start: "2025-06-19",
      color: "#aaaaaa",
      extendedProps: { org: "KAIST", host: "Juho Kim", place: "Daejeon, South Korea", type: "badge-talk", past: true }
    },
    {
      title: "Entangled with Books (independent bookstore)",
      start: "2025-06-17",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "", place: "Seoul, South Korea", type: "badge-talk", past: true }
    },
    {
      title: "Dept. of Political Science & IR",
      start: "2025-06-13",
      color: "#aaaaaa",
      extendedProps: { org: "Yonsei University", host: "Inbok Rhee", place: "Seoul, South Korea", type: "badge-talk", past: true }
    },
    {
      title: "Graduate School of International Studies",
      start: "2025-06-10",
      color: "#aaaaaa",
      extendedProps: { org: "Korea University", host: "Sunkyoung Park", place: "Seoul, South Korea", type: "badge-talk", past: true }
    },
    {
      title: "Code for America Summit",
      start: "2025-05-29",
      color: "#aaaaaa",
      url: "https://summit.codeforamerica.org/agenda/",
      extendedProps: { org: "", host: "", place: "Washington, DC, USA", type: "badge-panel", past: true }
    },
    {
      title: "What's next for CX in Government?",
      start: "2025-05-28",
      color: "#aaaaaa",
      extendedProps: { org: "", host: "Georgetown University's Better Government Lab", place: "Washington, DC, USA", type: "badge-participant", past: true }
    },
    {
      title: "Conference on Experimentation",
      start: "2025-05-23",
      color: "#aaaaaa",
      url: "https://datascience.stanford.edu/events/causal-science-center/stanford-causal-science-center-conference-experimentation",
      extendedProps: { org: "", host: "Stanford Causal Science Center", place: "Palo Alto, CA, USA", type: "badge-participant", past: true }
    },
    {
      title: "Organizing Forum",
      start: "2025-05-15",
      color: "#aaaaaa",
      url: "https://organizing.substack.com/",
      extendedProps: { org: "", host: "USC Equity Research Institute", place: "Los Angeles, CA, USA", type: "badge-participant", past: true }
    },
    {
      title: "American Politics Workshop",
      start: "2025-02-26",
      color: "#aaaaaa",
      url: "https://planitpurple.northwestern.edu/event/625048",
      extendedProps: { org: "Northwestern University", host: "", place: "Evanston, IL, USA", type: "badge-talk", past: true }
    }
  ];

  var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: 'dayGridMonth',
    height: 'auto',
    headerToolbar: {
      left: 'prev,next',
      center: 'title',
      right: ''
    },
    events: events,
    eventContent: function (arg) {
      var props  = arg.event.extendedProps;
      var isPast = props.past;
      var wrapper = document.createElement('div');
      wrapper.style.cssText = 'padding:2px 3px; white-space:normal; overflow:visible; line-height:1.4;';
      var titleEl = document.createElement('div');
      titleEl.style.cssText = 'font-weight:700; font-size:0.8em; color:#ffffff;';
      titleEl.textContent = arg.event.title;
      wrapper.appendChild(titleEl);
      if (props.org) {
        var orgEl = document.createElement('div');
        orgEl.style.cssText = 'font-size:0.76em; font-weight:700; color:#ffffff; margin-top:2px; text-decoration:underline; text-underline-offset:2px;';
        orgEl.textContent = props.org;
        wrapper.appendChild(orgEl);
      }
      if (props.host) {
        var hostEl = document.createElement('div');
        hostEl.style.cssText = 'font-size:0.73em; font-weight:700; color:#ffffff; margin-top:1px; font-style:italic;';
        hostEl.textContent = 'by ' + props.host;
        wrapper.appendChild(hostEl);
      }
      if (props.place) {
        var placeEl = document.createElement('div');
        var placeColor = isPast ? '#bbbbbb' : '#ffffff';
        placeEl.style.cssText = 'display:inline-block; font-size:0.72em; font-weight:600; color:' + placeColor + '; background:rgba(0,0,0,0.22); border-radius:3px; padding:1px 4px; margin-top:3px;';
        placeEl.textContent = props.place;
        wrapper.appendChild(placeEl);
      }
      return { domNodes: [wrapper] };
    },
    eventDidMount: function (info) {
      if (info.event.extendedProps.past) {
        info.el.style.opacity = '0.55';
      }
    },
    eventClick: function (info) {
      info.jsEvent.preventDefault();
      if (info.event.url) {
        window.open(info.event.url, '_blank');
      } else {
        var props = info.event.extendedProps;
        var msg = info.event.title;
        if (props.place) msg += '\n' + props.place;
        alert(msg);
      }
    }
  });

  calendar.render();
});

