// Auto-generated from index.qmd by generate_calendar.R
// Do not edit this file directly.

document.addEventListener("DOMContentLoaded", function () {
  var list = document.getElementById("landing-talk-list");
  if (!list) return;
  list.innerHTML = `      <li><time datetime="2026-05-01">May 1.</time> <a href="https://rohanalexander.com/tdw.html?fbclid=IwY2xjawRPEctleHRuA2FlbQIxMABicmlkETFwd0pSVVhHN2xaTTd2ZEY4c3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHrpKC20cB6deQ9gpFVoU0pkbwykSlhKol_1prTn6yWqn5Uj4YFUF6inmY9d3_aem_gfy7-jwggUYKf-t_TLT_Vw">The Future of Quantitative Social Science in an Age of Artificial Intelligenc, University of Toronto</a></li>
      <li><time datetime="2026-05-21">May 21.</time> <a href="https://politics.korea.ac.kr/kupolitics_kor/community/grad_school.do?mode=view&amp;articleNo=804673&amp;article.offset=0&amp;articleLimit=10&amp;totalNoticeYn=N&amp;totalBoardNo&amp;fbclid=IwY2xjawRPEeRleHRuA2FlbQIxMABicmlkETFwd0pSVVhHN2xaTTd2ZEY4c3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHsSLrFD-TJ9pjZXdolPqX79MkzjxQEvOtKUN_ddPlxued1JrXzLuFAgbdgAj_aem_fhq3jLsOEWuShEhMULwhMA">AI and Social Sciences, Department of Political Science and International Relations, Korea University</a></li>
      <li><time datetime="2026-06-11">June 11.</time> <a href="https://fas.org/">Source Code AI Trust &amp; Fairness Launch Event, Federation of American Scientists</a></li>
      <li><time datetime="2026-06-16">June 16-18.</time> <a href="https://summit.veritas.org/scholars-summit">2026 Veritas Scholars Summit</a></li>
      <li><time datetime="2026-09-03">Sept. 3-6.</time> <a href="https://connect.apsanet.org/apsa2026/">American Political Science Association (APSA) Annual Meeting</a></li>`;
});

