---
title: ""
---

### Book projects

1.  "Negotiating Identity in the American Welfare State: The Organizational Origin of Multiracial America." (based on [dissertation](https://escholarship.org/content/qt3531f8fr/qt3531f8fr.pdf))

    -   Interviewed by [Scope Conditions podcast](https://www.scopeconditionspodcast.com/episodes/episode-34-comparing-asian-coalitions-across-three-chinatowns-with-jae-yeon-kim?fbclid=IwAR1_zGE57lmVDhg8uQA8FfDbdzOybB704Q2m0VQkkhfWtB7Asj29I_-mxPM) (co-hosted by Alan Jacobs (UBC) and Yang-Yang Zhou (Dartmouth))

    -   Winner of the 2022 Best Dissertation Award, Urban and Local Politics, APSA

    -   Winner of the 2020 Best Paper Award, Asian Pacific American Politics, WPSA

    -   Interactive maps: [Asian American CBO](https://felt.com/map/Asian-American-CBO-SbkRl0sGTVWpp0FYYCXngC?loc=35.51,-114.14,3.89z), [Latino CBO](https://felt.com/map/Latino-CBO-A9ClV2KloSPeopHhGNnHtsB?loc=35.38,-96.98,4.64z)

    -   Datasets: [Asian American and Latino Advocacy and Community Service Organizations Dataset (1868-2016)](https://doi.org/10.7910/DVN/FLUPBJ)

America is a racially hierarchical society. However, ethnic groups with shared experiences of racial discrimination have not always joined forces politically. This book identifies the conditions under which ethnic elites decided to join forces as racial groups by leveraging the case of Asian Americans and Latinos. Before the late 1960s, national origin groups from Asia and Latin America did not come together as Asian Americans and Latinos. Their mobilization strategy shifted during this historical juncture because of the policy changes. Lyndon B. Johnson's War on Poverty programs expanded the American welfare state; however, these new safety net programs were implemented within the existing biracial framework. Street-level bureaucrats faced difficulty in classifying disadvantaged ethnic groups that did not fit into this prevalent image of the minority group. In response, non-target groups solved this collective problem by reinventing and organizing themselves in racial terms. This book traces this origin story by examining the parallel emergence of Asian American and Latino community organizing, which preceded their electoral politics. It also assesses the argument's scope conditions by comparing the variations in interethnic coalition formation in Chinatowns across the U.S. and Canadian border. Finally, it identifies the limitations of this contingent and relational identity formation theory in the contemporary period of racial threats, awakenings, and underlying demographic changes. The American multiracial framework we take for granted today has historical and organizational roots. Managing diversity from the top down is deeply intertwined with mobilizing diversity from the bottom up.

### Books

1.  ["Public Interest Data Science: Harnessing Data for Good."](http://www.sejongbooks.co.kr/?act=board.index&bbs_code=sub2_1&sc=bbs_title&ss=%EC%9A%B0%EB%A6%AC%EC%97%90%EA%B2%8C%EB%8A%94&page=1&bbs_mode=view&bbs_seq=160) (in Korean, Sejong Books 2023) \[[book website](https://civicdatascience.wordpress.com/)\]

    -   Recommended by [the *National Assembly Library*](https://shorturl.at/7Oc1Z), *Samsung Global Research*'s executive education program (SERICEO), [the *Korea Institute of Science and Technology* (KIST)](https://library.kist.re.kr/search/recommend.do)
    -   Featured in [*The Chosun Ilbo*](https://futurechosun.com/archives/80334), [*Maeil Business Newspaper*](https://www.mk.co.kr/news/culture/10825533), [*The Korea Economic Daily*](https://www.hankyung.com/article/202309136820i), [*Kyunghyang Shinmun*](https://www.khan.co.kr/culture/book/article/202309082034005), [*Hankyoreh*](https://h21.hani.co.kr/arti/world/world_general/54378.html) (major Korean newspapers across the ideological spectrum)